version: 2.1

orbs:
  terraform: circleci/terraform@3.6.0
jobs:
  tflint_backend:
    docker:
      - image: hashicorp/terraform:1.7
        entrypoint: /bin/sh
    resource_class: small 
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
              apk --upgrade --no-cache add curl unzip
              curl -L -o tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.45.0/tflint_linux_amd64.zip
              unzip tflint.zip
              rm -f tflint.zip
      - run: cd remote-state && ../tflint --minimum-failure-severity=error

  terraform_plan_backend:
    docker:
      - image: hashicorp/terraform:1.7
    resource_class: small
    steps:
      - checkout
      - run: terraform -chdir=remote-state init
      - run: terraform -chdir=remote-state plan -out=tf-backend.plan

  terraform_apply_backend:
      docker:
        - image: hashicorp/terraform:1.7
      resource_class: small
      steps:
        - checkout
        - run: terraform -chdir=remote-state init
        - run: terraform -chdir=remote-state plan -out=tf-backend.plan
        - run: terraform -chdir=remote-state apply tf-backend.plan

  tflint_region:
    docker:
      - image: hashicorp/terraform:1.7
        entrypoint: /bin/sh
    resource_class: small
    parameters:
      region:
        description: "AWS region to deploy to"
        type: string
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
              apk --upgrade --no-cache add curl unzip
              curl -L -o tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.45.0/tflint_linux_amd64.zip
              unzip tflint.zip
              rm -f tflint.zip
      - run: cd <<parameters.region>> && ../tflint --minimum-failure-severity=error

  tflint_global:
    docker:
      - image: hashicorp/terraform:1.7
        entrypoint: /bin/sh
    resource_class: small
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
              apk --upgrade --no-cache add curl unzip
              curl -L -o tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.45.0/tflint_linux_amd64.zip
              unzip tflint.zip
              rm -f tflint.zip
      - run: cd global && ../tflint --minimum-failure-severity=error

  terraform_plan_region:
    docker:
      - image: hashicorp/terraform:1.7
    resource_class: small
    parameters:
      region:
        description: "AWS region to deploy to"
        type: string
    steps:
      - checkout
      - run: 
          name: Set Terraform environment variables from Splunk context
          command: |
            export TF_VAR_hec_host="$SPLUNK_COLLECTOR_URL"
            export TF_VAR_hec_token="$SPLUNK_HEC_TOKEN"
            
            # Create terraform.tfvars file
            cat > <<parameters.region>>/terraform.tfvars \<< EOF
            # Path to the Lambda function zip file
            lambda_zip_path = "../src/SplunkLambdaCloudWatchLogsProcessor.zip"

            # Splunk HEC host URL
            hec_host = "$SPLUNK_COLLECTOR_URL"

            # Splunk HEC token
            hec_token = "$SPLUNK_HEC_TOKEN"

            # ELB cookie name (if applicable)
            elb_cookie_name = ""
            EOF
      - run: terraform -chdir=<<parameters.region>> init 
      - run: terraform -chdir=<<parameters.region>> plan -var-file=terraform.tfvars -out=tf-<<parameters.region>>.plan

  terraform_plan_global:
    docker:
      - image: hashicorp/terraform:1.7
    resource_class: small
    steps:
      - checkout
      - run: terraform -chdir=global init 
      - run: terraform -chdir=global plan -out=tf-global.plan

  terraform_apply_region:
    docker:
      - image: hashicorp/terraform:1.7
    resource_class: small
    parameters:
      region:
        description: "AWS region to deploy to"
        type: string
    steps:
      - checkout
      - run: 
          name: Set Terraform environment variables from Splunk context
          command: |
            export TF_VAR_hec_host="$SPLUNK_COLLECTOR_URL"
            export TF_VAR_hec_token="$SPLUNK_HEC_TOKEN"
            
            cat > <<parameters.region>>/terraform.tfvars \<< EOF
            # Path to the Lambda function zip file
            lambda_zip_path = "../src/SplunkLambdaCloudWatchLogsProcessor.zip"

            # Splunk HEC host URL
            hec_host = "$SPLUNK_COLLECTOR_URL"

            # Splunk HEC token
            hec_token = "$SPLUNK_HEC_TOKEN"

            # ELB cookie name (if applicable)
            elb_cookie_name = ""
            EOF
      - run: terraform -chdir=<<parameters.region>> init 
      - run: terraform -chdir=<<parameters.region>> plan -var-file=terraform.tfvars -out=tf-<<parameters.region>>.plan
      - run: terraform -chdir=<<parameters.region>> apply tf-<<parameters.region>>.plan

  terraform_apply_global:
    docker:
      - image: hashicorp/terraform:1.7
    resource_class: small
    steps:
      - checkout
      - run: terraform -chdir=global init
      - run: terraform -chdir=global plan -out=tf-global.plan
      - run: terraform -chdir=global apply tf-global.plan

workflows:
  tflint_and_plan:
    jobs:
      - tflint_backend:
          name: tflint-backend
      - terraform_plan_backend:
          name: terraform-plan-backend
          requires: 
            - tflint-backend
          context:
            - aws
      - approval:
          name: backend-approval
          type: approval
          requires:
            - terraform-plan-backend
          filters:
            branches:
              only:
                - main
          context:
            - aws            
      - terraform_apply_backend:
          name: terraform-apply-backend
          requires:
            - backend-approval
          filters:
              branches:
                only:
                  - main
          context:
            - aws
      - tflint_region:
          name: tflint-<<matrix.region>>
          matrix:
            parameters:
              region: ["us-east-1", "eu-central-1"]    
      - tflint_global:
          name: tflint-global
      - terraform_plan_region:
          name: terraform-plan-<<matrix.region>>
          requires:
            - tflint-<<matrix.region>>
            - terraform-apply-backend
          matrix:
            parameters:
              region: ["us-east-1", "eu-central-1"]    
          context: 
            - aws
            - splunk
      - terraform_plan_global:
          name: terraform-plan-global
          requires:
            - tflint-global
            - terraform-apply-backend
          context: aws      
      - approval:
          name: global-approval
          type: approval
          requires: 
            - terraform-plan-global
          filters:
            branches:
              only:
                - main
      - terraform_apply_global:
          name: terraform-apply-global
          requires:
            - global-approval
          context: aws
          filters:
            branches:
              only:
                - main     
      - approval:
          name: region-approval
          type: approval
          requires: 
            - terraform-plan-us-east-1
            - terraform-plan-eu-central-1
          filters:
            branches:
              only:
                - main
      - terraform_apply_region:
          name: terraform-apply-<<matrix.region>>
          requires:
            - region-approval
          matrix:
            parameters:
              region: ["us-east-1", "eu-central-1"]    
          context: 
            - aws
            - splunk
          filters:
            branches:
              only:
                - main
