# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.6.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  tflint:
    docker:
      - image: cimg/base:current
    resource_class: small
    parameters:
      region:
        description: "AWS region to deploy to"
        type: string
    steps:
      - checkout
      - run:
          name: Install tflint
          command: |
            apk --upgrade --no-cache add curl unzip
            curl -L -o tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.45.0/tflint_linux_amd64.zip
            unzip tflint.zip
            rm -f tflint.zip
      - run: cd <<parameters.region>> && tflint
  terraform_plan:
    docker:
      - image: cimg/base:current
    resource_class: small
    parameters:
      region:
        description: "AWS region to deploy to"
        type: string
    steps:
      - checkout
      - run: terraform -chdir=<<parameters.region>> init 
      - run: terraform -chdir=<<parameters.region>> plan -var-file=terraform.tfvars

workflows:
  tflint_and_plan:
    jobs:
      - tflint
      - terraform_plan:
          requires:
            - tflint
          parameters:
            region: ["global", "us-east-1", "us-west-2"]
          context: aws
      - terraform_plan:
          requires:
            - tflint
          parameters:
            region: ["global", "us-east-1", "us-west-2"]
          context: aws