# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.6.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  tflint:
    docker:
      - image: cimg/base:current
    resource_class: small
    parameters:
      region:
        description: "AWS region to deploy to"
        type: string
    steps:
      - setup_remote_docker
      - checkout
      #- run: ls -la && ls -la ../ && ls -la ../.. && ls -la ../../..
      - run:  docker run --rm -v $(pwd):/data -t --entrypoint /bin/sh ghcr.io/terraform-linters/tflint -c "tflint --init && ls -la && cd <<parameters.region>>/ && tflint"
      #- run: cd <<parameters.region>> && ../.tflint
  terraform_plan:
    docker:
      - image: cimg/base:current
    resource_class: small
    parameters:
      region:
        description: "AWS region to deploy to"
        type: string
    steps:
      - checkout
      - run: terraform -chdir=<<parameters.region>> init 
      - run: terraform -chdir=<<parameters.region>> plan -var-file=terraform.tfvars

workflows:
  tflint_and_plan:
    jobs:
      - tflint:
          matrix:
            parameters:
              region: ["global", "us-east-1", "us-west-2"]    
      - terraform_plan:
          requires:
            - tflint
          matrix:
            parameters:
              region: ["global", "us-east-1", "us-west-2"]    
          context: aws
