version: 2.1

orbs:
  terraform: circleci/terraform@3.6.0
jobs:
  tflint_backend:
    docker:
      - image: hashicorp/terraform:1.7
        entrypoint: /bin/sh
    resource_class: small 
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
              apk --upgrade --no-cache add curl unzip
              curl -L -o tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.45.0/tflint_linux_amd64.zip
              unzip tflint.zip
              rm -f tflint.zip
      - run: cd remote-state && ../tflint --minimum-failure-severity=error

  terraform_plan_backend:
    docker:
      - image: hashicorp/terraform:1.7
    resource_class: small
    steps:
      - checkout
      - run: terraform -chdir=remote-state init
      - run: terraform -chdir=remote-state plan -out=tf-backend.plan

  terraform_destroy_backend:
      docker:
        - image: hashicorp/terraform:1.7
      resource_class: large
      steps:
        - checkout
        - run: terraform -chdir=remote-state init
        - run: terraform -chdir=remote-state plan -out=tf-backend.plan
        - run: terraform -chdir=remote-state destroy -auto-approve

workflows:
  terraform_plan_and_destroy:
    jobs:
      - tflint_backend:
          name: tflint-backend
      - terraform_plan_backend:
          name: terraform-plan-backend
          requires: 
            - tflint-backend
          context:
            - aws
      - approval:
          name: backend-destroy-approval
          type: approval
          requires:
            - terraform-plan-backend
          filters:
            branches:
              only:
                - main
          context:
            - aws  
      - terraform_destroy_backend:
          name: terraform-destroy-backend
          requires:
            - backend-destroy-approval
          filters:
              branches:
                only:
                  - main
          context:
            - aws




